SELECT CURRENT_VERSION();

SELECT CURRENT_ROLE();
SELECT CURRENT_AVAILABLE_ROLES();
SELECT CURRENT_SECONDARY_ROLES();
USE SECONDARY ROLE ALL;
SELECT CURRENT_SECONDARY_ROLES();
USE SECONDARY ROLE NONE;

SELECT CURRENT_SESSION();
SELECT CURRENT_USER();

select current_warehouse(), current_database(), current_schema();
select current_date, current_time, current_timestamp;

SELECT ALL_USER_NAMES();