USE ROLE ACCOUNTADMIN;
USE WAREHOUSE INSTRUCTOR1_WH;
USE DATABASE SNOWFLAKE;
USE SCHEMA ACCOUNT_USAGE;

-- NOT CLONES
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS WHERE ID = CLONE_GROUP_ID;

-- CLONES	
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS WHERE ID <> CLONE_GROUP_ID;