-- SHARING, READER AND ROW-BASED ACCESS DEMO
-- THREE ACCOUNTS NEEDED FOR LAB
-- YOUR CURRENT ACCOUNT AS PROVIDER, REFERENCED AS PRO11111 BELOW
-- AN ACCOUNT FROM A PRIOR CLASS AS CONSUMER, REFERENCED AS CON22222 BELOW
-- 		CONSUMER IS NOT ESSENTIAL IF YOU DO NOT HAVE ANOTHER ACCOUNT
-- A MANAGED ACCOUNT, CREATED BELOW, AS READER, REFERENCED AS RED33333 BELOW

USE ROLE TRAINING_ROLE;
USE WAREHOUSE INSTRUCTOR1_WH;
USE DATABASE INSTRUCTOR1_DB;
USE SCHEMA PUBLIC;

-- CREATE PARTNER MONTHLY SALES TABLE IN INSTRUCTOR1_DB
CREATE OR REPLACE TABLE MONTHLY_SALES (EMPID NUMBER, AMOUNT NUMBER, MONTH VARCHAR(100));

INSERT INTO MONTHLY_SALES (EMPID, AMOUNT, MONTH) VALUES
	(	1, 10000,	'JAN'	)
, (	1,   400,	'JAN'	)
,	(	2,  4500,	'JAN'	)
, (	2, 35000,	'JAN'	)
,	(	3,  5000,	'JAN'	)
, (	3, 30000,	'JAN'	)
,	(	1, 10000,	'FEB'	)
, (	1,   400,	'FEB'	)
,	(	2,  4500,	'FEB'	)
, (	2, 35000,	'FEB'	)
,	(	3,  5000,	'FEB'	)
, (	3, 30000,	'FEB'	)
,	(	1, 10000,	'MAR'	)
, (	1,  4000,	'MAR'	)
,	(	2,  4000,	'MAR'	)
, (	2,  5000,	'MAR'	)
,	(	3,  5000,	'MAR'	)
, (	3, 11000,	'MAR'	)
,	(	1, 10000,	'APR'	)
, (	1,  1400,	'APR'	)
,	(	2,  4500,	'APR'	)
, (	2, 22000,	'APR'	)
,	(	3,  8000,	'APR'	)
, (	3, 18000,	'APR'	)
;

SELECT * FROM MONTHLY_SALES;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

GRANT ROLE TRAINING_ROLE TO ROLE ACCOUNTADMIN;

-- YOU MUST BE AN ACCCOUNTADMIN TO WORK WITH SHARES
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;

-- CREATE THE READER ACCOUNT
-- MODIFY MANAGED ACCOUNT NAME (INST1_READER_NEW), IN LINE BELOW, TO BE UNIQUE ONLY IF NEEDED
  CREATE MANAGED ACCOUNT INST1_READER_NEW
   ADMIN_NAME = READER, ADMIN_PASSWORD = 'Test12345', TYPE = READER;
-- NOTE THE OUTPUT OF THIS COMMAND. IT IS A SNOWFLAKE ID AND URL
-- COPY AND PASTE BELOW FOR REFERENCE IN LATER COMMANDS

-- I.E. RED33333 HTTPS://RED33333.SNOWFLAKECOMPUTING.COM
-- NOTE THE ACCOUNT NAME AND URL FOR THE READER ACCOUNT!!!!

-- CREATE A DATABASE AND TABLE TO SHARE
USE ROLE TRAINING_ROLE;
CREATE OR REPLACE DATABASE INSTRUCTOR1_SHARED_DB;
USE DATABASE INSTRUCTOR1_SHARED_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE REF (ID NUMBER, ACCT STRING);

-- NOTE: YOU MUST ENTER ALL ACCOUNT NAMES IN COMMAND BELOW
USE WAREHOUSE INSTRUCTOR1_WH;

DELETE FROM REF;

-- FOR PROVIDER ACCOUT USE CURRENT ACCOUNT, THIS WILL MAP TO ID 1
-- FOR CONSUMER ACCOUNT USE A DEPLOYMENT FROM A PRIOR CLASS, THIS WILL MAP TO ID 2
-- FOR READER ACCOUNT COPY INFORMATION FROM ABOVE, THIS WILL MAP TO ID 3

SELECT CURRENT_ACCOUNT(); 
-- PUT PROVIDER (YOUR CURRENT ACCOUNT) IN ID 1, CONSUMER IN ID 2 AND READER IN ID 3 
INSERT INTO REF VALUES (1, 'PRO11111'), (2, 'CON22222'), (3, 'RED33333');

SELECT * FROM REF;

-- SAMPLE OUTPUT
-- Row	ID	ACCT
-- 1		1		PRO11111
-- 2		2		CON22222
-- 3		3		RED33333
 
-- CREATE VIEWS POINTING TO TABLES IN MULTIPLE DATABASES WITH ROW ACCESS POLICY 
CREATE OR REPLACE SECURE VIEW MONTHLY_SALES_SHARED
AS SELECT *
  FROM INSTRUCTOR1_DB.PUBLIC.MONTHLY_SALES MS
  JOIN REF ON REF.ID = MS.EMPID
  AND REF.ACCT = CURRENT_ACCOUNT();

-- NON-SECURE VIEW TO DEMONSTRATE SECURE REQUIREMENT
CREATE OR REPLACE VIEW NOTSECURE_SALES_SHARED
AS SELECT *
  FROM INSTRUCTOR1_DB.PUBLIC.MONTHLY_SALES MS
  JOIN REF ON REF.ID = MS.EMPID
  AND REF.ACCT = CURRENT_ACCOUNT();  

SELECT * FROM INSTRUCTOR1_DB.PUBLIC.MONTHLY_SALES;

-- SHOULD ONLY SEE RECORDS FOR ID 1 SALES IF REF WAS CREATED CORRECTLY ABOVE
SELECT * FROM MONTHLY_SALES_SHARED;

SELECT * FROM NOTSECURE_SALES_SHARED;

-- THIS WORKS SINCE WE CREATED THE SECURE VIEW, BUT WILL NOT FOR OTHERS
SELECT GET_DDL('VIEW', 'MONTHLY_SALES_SHARED');

-- THIS WILL WORK FOR ALL ROLES
SELECT GET_DDL('VIEW', 'NOTSECURE_SALES_SHARED');

-- CREATE THE SHARE, CHANGE NAME IF NEEDED
CREATE SHARE INSTRUCTOR1_MS_SHARE0301;

-- GRANT PRIVILEGES ON THE SHARE

GRANT USAGE ON DATABASE INSTRUCTOR1_SHARED_DB TO SHARE INSTRUCTOR1_MS_SHARE0301;

GRANT USAGE ON SCHEMA PUBLIC TO SHARE INSTRUCTOR1_MS_SHARE0301;

-- THIS WILL FAIL SINCE SECURE VIEW REFERENCES NON-SHARED DATABASE
GRANT SELECT ON MONTHLY_SALES_SHARED TO SHARE INSTRUCTOR1_MS_SHARE0301;

-- WE ARE NOT SHARING THE DATABASE WHERE THE MONTHLY SALES ARE, TO OVERCOME THIS
-- WE NEED REFERENCE USAGE ON THE NON-SHARED DATABASE FOR THE SHARE
GRANT REFERENCE_USAGE ON DATABASE INSTRUCTOR1_DB TO SHARE INSTRUCTOR1_MS_SHARE0301;

GRANT SELECT ON MONTHLY_SALES_SHARED TO SHARE INSTRUCTOR1_MS_SHARE0301;

--BELOW WILL FAIL, CANNOT SHARE AN UNSECURED VIEW
GRANT SELECT ON NOTSECURE_SALES_SHARED TO SHARE INSTRUCTOR1_MS_SHARE0301;

-- ADD THE NEW CONSUMER AND READER ACCOUNT (I.E. CON22222, RED33333) TO THE SHARE. CHANGE BELOW:
-- WE ALSO USE 'SHARE_RESTRICTIONS = FALSE' IF NEEDED TO SHARE WITH LOWER VERSIONS OF SNOWFLAKE 
ALTER SHARE INSTRUCTOR1_MS_SHARE0301 ADD ACCOUNTS=CON22222,RED33333 SHARE_RESTRICTIONS=FALSE;


//
// LOG IN TO CONSUMER ACCOUNT, I.E. HTTPS://CON22222.SNOWFLAKECOMPUTING.COM
// ASSUMING USER IS INSTRUCTOR1, OR A MEMBER OF TRAINING_ROLE AND ACCOUNTADMIN
// EXECUTE THESE STEPS FROM CONSUMER ACCOUNT

-- CHANGE DATA PROVIDER BELOW, EX. PRO11111
-- CHANGE SHARE NAME (INSTRUCTOR1_MS_SHARE0301) ONLY IF NEEDED
USE ROLE ACCOUNTADMIN;
CREATE DATABASE MS_READONLY FROM SHARE PRO11111.INSTRUCTOR1_MS_SHARE0301;
GRANT IMPORTED PRIVILEGES ON DATABASE MS_READONLY TO ROLE TRAINING_ROLE;

USE ROLE TRAINING_ROLE;
CREATE OR REPLACE WAREHOUSE INSTRUCTOR1_WH WAREHOUSE_SIZE=SMALL INITIALLY_SUSPENDED=TRUE;
USE WAREHOUSE INSTRUCTOR1_WH;
USE DATABASE MS_READONLY;
USE SCHEMA PUBLIC;

-- SHOULD ONLY SEE RECORDS FOR ID 2 SALES IF REF WAS CREATED CORRECTLY ABOVE
SELECT * FROM MS_READONLY.PUBLIC.MONTHLY_SALES_SHARED;


//
// LOG IN TO READER ACCOUNT
// EXECUTE THESE STEPS FROM READER ACCOUNT
//
//
// LOG INTO THE READER URL:  EX. HTTPS://RED33333.SNOWFLAKECOMPUTING.COM
// LOG IN WITH USERNAME: READER 
// AND PASSWORD: Test12345 
// CANCEL THE POPUP DIALOG BOX
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE READER_WH WAREHOUSE_SIZE=LARGE INITIALLY_SUSPENDED=TRUE;
GRANT USAGE ON WAREHOUSE READER_WH TO ROLE PUBLIC;

-- CHANGE DATA PROVIDER BELOW, EX. PRO11111
-- CHANGE SHARE NAME (INSTRUCTOR1_MS_SHARE0301) ONLY IF NEEDED
CREATE DATABASE MS_READONLY FROM SHARE PRO11111.INSTRUCTOR1_MS_SHARE0301;
GRANT IMPORTED PRIVILEGES ON DATABASE MS_READONLY TO ROLE PUBLIC;

USE ROLE PUBLIC;
USE DATABASE MS_READONLY;
USE SCHEMA PUBLIC;
USE WAREHOUSE READER_WH;

-- SHOULD ONLY SEE RECORDS FOR ID 3 SALES IF REF WAS CREATED CORRECTLY ABOVE
SELECT * FROM MS_READONLY.PUBLIC.MONTHLY_SALES_SHARED;

-- THE DATA AND THE COMPUTE ARE ALL ON PROVIDER, SO IT TAKES A LITTLE LONGER.
-- SHOULD ONLY SEE RECORDS FOR READER ACCOUNT SALES
//
//
// GO BACK TO PROVIDER
//
//

DROP MANAGED ACCOUNT "INST1_READER_NEW";
DROP SHARE INSTRUCTOR1_MS_SHARE0301;
DROP DATABASE INSTRUCTOR1_SHARED_DB;


-- GO BACK TO CONSUMER AND READER ACCOUNT AND LOOK FOR SHARE